### ISSUE TITLE
the recent post listing on the blog does not match the visible number of posts

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-web-site#111]
It is kind of strange that there is a list of recent posts with the latest 6 posts and the front page only shows the last 5.

Also since our posts are quite long the blog main page gets way to much scroll

Maybe we should just show 1 post on the main page?

**Comment by cescoffier** [comment]
It should be 6 and 6. 

We can only display an excerpt on the first page with a "read more" link ?

**Comment by pmlopes** [comment]
yes a read more would be nice the we can have something sensible on the first page

**Comment by michel-kraemer** [comment]
I can implement this when I have time on the weekend if you like.
