### ISSUE TITLE
we should have a list of all post from the blog

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-web-site#113]
We can only see a list of the last 6 posts on the blog all other posts are not listed, unless we jump to a older post and the list start counting down from that post.

This means that posts like how to use NPM and the nice collection of post from Clement on how to start from scratch a full working application are "lost" (by lost i mean not easily found).

I think we should have this list or at least something like blogger, a list grouped by year/month

**Comment by cescoffier** [comment]
This would be awesome do have this. 

This is just a list right now, because the technology we use does not provide anything to do that (so we have to do that manually). I will have a look.

**Comment by michel-kraemer** [comment]
Please review #115. Thanks!

Michel

**Comment by michel-kraemer** [comment]
@cescoffier Ping! :-) :-)

**Comment by cescoffier** [comment]
oupsy, sorry, went out from my radar. Will test it on my way to devoxx, and let you know tonight or tomorrow.

**Comment by michel-kraemer** [comment]
No hurry! If you're busy with devoxx I'm totally fine with waiting a couple of days longer. Enjoy the conference. I wish I was there!

**Comment by cescoffier** [comment]
Hi,

I've checked in in the plane, it looks great. Only small things on the archive page what about doing:

```
<span class="blog-archives-day">{{ post.date | date }}:
```

So we get the complete date and not just the day (which looked weird to me on the first look). 

(the `date` filter uses _moment_ to get a nicely formatted date).

**Comment by michel-kraemer** [comment]
@cescoffier OK. Thanks for the review. I updated the PR.

It looked kind of odd after replacing `day` by `date` (not aligned anymore) so I put the date and the title in different grid columns. Now the page is also responsive.

Cheers,
Michel
