### ISSUE TITLE
Building the site fails right after cloning

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/vertx-web-site#114]
If you clone the repository, cd into it and issue a `mvn site` like it is described in the README, it will fail because it cannot find `data.json` in the target directory. It seems the file is not created before Gulp is called.

A workaround is to call `mvn process-resources` first and then `mvn site`.

I know too little about Maven to fix this issue myself.

Cheers,
Michel

**Comment by cescoffier** [comment]
It's because we rely on resoruce filtering. Will fix this to execute it in the site lifecycle.
