### ISSUE TITLE
Addition to Who's Using

### ISSUE THREAD

**Issue by andyhedges** [vert-x3/vertx-web-site#137]
Hi, we would be happy if you'd like to add our logo to the "who's using vert.x" section.

![tesco-logo-whiteout-180px](https://cloud.githubusercontent.com/assets/958352/12695274/e47965a2-c740-11e5-831e-91b35fcbd521.png).

Logo is attach (it's white with a transparent background - but it's just above...)

**Comment by jclingan** [comment]
Andy, thanks for your willingness to let the vert.x project use the Tesco logo. Do you have business approval to have the Tesco logo used in vendor (Red Hat) presentations? It would be nice to show the logo on Red Hat Vert.x presentations.
