### ISSUE TITLE
Fix thymeleaf template engine example

### ISSUE THREAD

**Issue by igouss** [vert-x3/vertx-web-site#138]
Formatting looks wrong http://vertx.io/docs/vertx-web/java/#_thymeleaf_template_engine
[snip]
&lt;p th:text="${context.get('foo')}"&gt;&lt;/p&gt;
&lt;p th:text="${context.get('bar')}"&gt;&lt;/p&gt;
&lt;p th:text="${context.normalisedPath()}"&gt;&lt;/p&gt;
&lt;p th:text="${context.request().params().get('param1')}"&gt;&lt;/p&gt;
&lt;p th:text="${context.request().params().get('param2')}"&gt;&lt;/p&gt;
[snip]

Do not escape < and >

**Comment by cescoffier** [comment]
Changes integrated in the web site.
