### ISSUE TITLE
wrong common sql example?

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#148]
Hi there:

http://vertx.io/docs/vertx-sql-common/java/
in this section: Executing INSERT, UPDATE or DELETE
the code example(with black background) of this section is actually irrelevant
it should be something like connection.update("INSERT INTO ....");
does it make sense?

Thanks

**Comment by cescoffier** [comment]
ISsue fixed in the project. The web site is going to be updated during the next release.
