### ISSUE TITLE
"Deploying Verticle instances" not available in Java

### ISSUE THREAD

**Issue by w0mbat** [vert-x3/vertx-web-site#149]
I just looked through the documentation (http://vertx.io/docs/vertx-core/java/) and it states, that `Deploying Verticle instances is Java only` - but once I do code-completion, this method is not available - "only" name based deployment can be used

**Comment by chengenzhao** [comment]
Hi there:

I just try deploying instance and it works for me though:

    public static void main(String[] args){
        Vertx vertx = Vertx.vertx();
        HttpServerVerticle verticle = new HttpServerVerticle();
        vertx.deployVerticle(verticle);
    }

hope it helps

cheers

**Comment by michel-kraemer** [comment]
Thanks, @chengenzhao for the code example. @w0mbat, I hope it helps. If not, please ask the question again on the [Google user group](https://groups.google.com/forum/?fromgroups#!forum/vertx). GitHub is only for issues and not for questions. You will get more answers on the user group. Thanks.

**Comment by w0mbat** [comment]
@chengenzhao @michel-kraemer For the regular Vertx this is true, but not for the rxjava implementation - I forgot to mention it. Should there be differences?

**Comment by cescoffier** [comment]
@w0mbat for RX, you should use `vertx.getDeletage().deployVerticle(...)`.
But as said by @michel-kraemer, please you the google group to ask questions.
