### ISSUE TITLE
Failing a Future needs a message or Throwable

### ISSUE THREAD

**Issue by w0mbat** [vert-x3/vertx-web-site#150]
I just copy/pasted this example from the offical guide(http://vertx.io/docs/vertx-core/java/):
```
public void start(Future<Void> startFuture) {
    // Now deploy some other verticle:

    vertx.deployVerticle("com.foo.OtherVerticle", res -> {
      if (res.succeeded()) {
        startFuture.complete();
      } else {
        startFuture.fail();
      }
    });
  }
```
and it fails compiling because fail() cannot have zero parameters - it needs at least a message or throwable

**Comment by cescoffier** [comment]
Yes it should be `startFuture.fail(res.cause())`.

**Comment by cescoffier** [comment]
Fix in https://github.com/eclipse/vert.x/pull/1372

**Comment by cescoffier** [comment]
Closing this one as the PR has been merged. It will be updated with the next release.
