### ISSUE TITLE
"SockJS event bus bridge" mistake

### ISSUE THREAD

**Issue by tuler** [vert-x3/vertx-web-site#158]
At "SockJS event bus bridge", "Securing the Bridge", when describing inbound and outbound rules:

"If a message is out-bound (i.e. being sent from the server to client side JavaScript) before it is sent to the client Vert.x-Web will look through any ~~inbound~~ **outbound** permitted matches. If any match, it will be allowed through."

**Comment by cescoffier** [comment]
Fixed in the vert.x web project.
Thanks for reporting !
