### ISSUE TITLE
compose future questions?

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#160]
Hi there:

According to the doc here:
http://vertx.io/docs/vertx-core/java/
"compose can be used for chaining futures:"
The future can be composed in this way:
//////////////////////
FileSystem fs = vertx.fileSystem();

Future<Void> fut1 = Future.future();

fs.createFile("/foo", fut1.completer());
fut1.compose(v -> {

  Future<Void> fut2 = Future.future();
  fs.writeFile("/foo", Buffer.buffer(), fut2.completer());

  // Compose fut1 with fut2
  return fut2;
}).compose(v -> {

  // Compose fut1 with fut2 and fut3
  fs.move("/foo", "/bar", startFuture.completer());
}, startFuture);
//////////////////////
but the questions is where is fut3 and also what is startFuture here?
I guess the code should be sth. like

//////////////////////
FileSystem fs = vertx.fileSystem();

Future<Void> fut1 = Future.future();
Future<Void> fut3 = Future.future();

fs.createFile("/foo", fut1.completer());
fut1.compose(v -> {

  Future<Void> fut2 = Future.future();
  fs.writeFile("/foo", Buffer.buffer(), fut2.completer());

  // Compose fut1 with fut2
  return fut2;
}).compose(v -> {

  // Compose fut1 with fut2 and fut3
  fs.move("/foo", "/bar", fut3.completer());
}, fut3);
//////////////////////
right?

and also about compose method in the javadoc, it is not very clear about the explanation

//////////////////////
compose

default <U> Future<U> compose(Handler<T> handler,
                              Future<U> composed)
Compose this future with a provided next future.
When this future succeeds, the handler will be called with the completed value, this handler should complete the next future.

If the handler throws an exception, the returned future will be failed with this exception.

When this future fails, the failure will be propagated to the next future and the handler will not be called.
//////////////////////
I guess the next future is the parameter "Future&lt;U&gt; composed" right?
Is it a better idea to change the object name "composed" to "nextFuture"?
and what does it mean by "this handler should complete the next future."? 
Does it mean the handler should trigger that next future? like fut2.completer() in the example? If there is no fut2.completer() in the handler, does the handler of fut2 will be executed?

And it would be great if some one could elaborate this part, it is not very clear about this part in the doc.

Thanks

**Comment by cescoffier** [comment]
Fixed in vertx-core.
