### ISSUE TITLE
Lighter primary color

### ISSUE THREAD

**Issue by michel-kraemer** [vert-x3/vertx-web-site#17]
We need to decide what shade of purple we will use as primary color:
https://groups.google.com/group/vertx/attach/5576ac2ed11b6db6/color-tests.png?part=0.1&authuser=0

Of course we also need to adapt the logo and the favicon.

@purplefox Do you have SVG files for the logo and the favicon?

**Comment by purplefox** [comment]
I think I prefer 3 or 4.

I'll see if I can find the svg files...

**Comment by purplefox** [comment]
Btw, Vert.x logo svg file has been uploaded to the wikipedia page :)

https://en.wikipedia.org/wiki/Vert.x#/media/File:Vert.x_Logo.svg

**Comment by purplefox** [comment]
What do you think about the colours Michel?

**Comment by michel-kraemer** [comment]
Well, if you want my opinion, I say colors 3 and 4 look good, but 1 is great as well. I would prefer 3 over 4, but I really can't decide between 1 and 3. If you think 1 is too dark, then we should go for 3. But if you don't have a strong opinion either, I'd say we leave it as it is.

**Comment by purplefox** [comment]
I prefer 3, how about we go for that
