### ISSUE TITLE
Sergey Mashkov adds himself to the Vert.x committers

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-web-site#175]
via a PR

**Comment by vietj** [comment]
@cy6erGn0m can you provide a PR for this ? thanks

**Comment by michel-kraemer** [comment]
@cy6erGn0m Any news here?

**Comment by michel-kraemer** [comment]
It seems @cy6erGn0m does not respond. Shall we close the issue?

**Comment by vietj** [comment]
no keep it open as reminder, we can do it ourselves eventually later
