### ISSUE TITLE
Eclipse Vert.x update

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-web-site#177]
Update with changes explained here : https://github.com/vert-x3/eclipse-proposal-wip/blob/master/proposal.adoc

**Comment by michel-kraemer** [comment]
Should I take care of this?

**Comment by cescoffier** [comment]
Up to you @michel-kraemer I can do it too.

**Comment by cescoffier** [comment]
@vietj commit need a bit of CSS magic ;-)

**Comment by michel-kraemer** [comment]
> commit need a bit of CSS magic ;-)

:smile: Oh, I just saw Julien's commit. Maybe he pushed it while I was typing. I can do the CSS magic on the weekend at the latest if you like.

**Comment by michel-kraemer** [comment]
OK. I fixed the footer in the `eclipse-vertx-update` branch. You may merge it if you like.

**Comment by vietj** [comment]
will have a look thanks!

**Comment by vietj** [comment]
@michel-kraemer I don't see the commit in the repo

**Comment by michel-kraemer** [comment]
Ooops. Pushed to origin instead of upstream. Sorry. It should be visible now.

**Comment by vietj** [comment]
@michel-kraemer nice, do you know why _Terms of Use_ and _Copyright Agent_ don't appear as links ?

**Comment by michel-kraemer** [comment]
Ah. Alright. I didn't see that. Fixed too now.

**Comment by vietj** [comment]
lol, my bad wrong HTML thanks!
