### ISSUE TITLE
java comments issue

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#192]
Hi there:

On the page: 
http://vertx.io/docs/vertx-web/java/#_templates
there is a comment:
// This will route all GET requests starting with /dynamic/ to the template handler
// E.g. /dynamic/graph.hbs will look for a template in /templates/**_dynamic_**/graph.hbs

but actually when we test it, the system actually looks for a template in /templates/graph.hbs
rather than "/templates/dynamic/graph.hbs" at the end of comment 
so here we should write /templates/dynamic/graph.hbs -> /templates/graph.hbs

we use thymeleaf template engine to do this task
not sure other templates

hope it helps

**Comment by chengenzhao** [comment]
Besides, i would recommend adding code piece into the sample.

Java code(in the verticle):

        TemplateEngine engine = ThymeleafTemplateEngine.create();
        TemplateHandler handler = TemplateHandler.create(engine);

        Router router = Router.router(vertx);

        **router.get("/dynamic/*").handler(routingContext -> {
            routingContext.put("key","Hello World!");
            routingContext.next();
        });**
        router.get("/dynamic/*").handler(handler);

        vertx.createHttpServer().requestHandler(router::accept).listen(8080);

Thymeleaf code piece:

<p th:text="${context.get('key')}"></p>

since we spend some times in investigating how to put the value in the routingContext, the bold part may lost when we use template.

**Comment by chengenzhao** [comment]
same error here:

"For example, if there was a request with path /static/css/mystyles.css the static serve will look for a file in the directory webroot/**static**/css/mystyle.css."

when we test it, the directory webroot/**static**/css/mystyle.css is actually webroot/css/mystyle.css

need to change webroot/**static**/css/mystyle.css -> webroot/css/mystyle.css

**Comment by cescoffier** [comment]
@pmlopes can you check ? (and probably move the issue to vert.x web)

**Comment by chengenzhao** [comment]
Hi cescoffier:

We checked the source code, and here is what we found:

  /**
   * Default value of the web-root, where files are served from
   */
  String DEFAULT_WEB_ROOT = "webroot";

in StaticHandler

and

  /**
   * The default directory where templates will be looked for
   */
  String DEFAULT_TEMPLATE_DIRECTORY = "templates";

in TemplateHandler

hope it helps

**Comment by chengenzhao** [comment]
My opinion, the way it currently works is correct, there is no need to add another directory like static or dynamic in defualt webroot or templates directory, because the files are already there and adding static or dynamic directory is apparently redundant. Besides if this is an issue of vertx-web then this breaking changes would become an huge impact on current codes.

**Comment by chengenzhao** [comment]
https://github.com/vert-x3/vertx-web/issues/618
