### ISSUE TITLE
Link does not work 

### ISSUE THREAD

**Issue by lynxluna** [vert-x3/vertx-web-site#193]
Just working on my vertx app, and tries to access the docs and surprised links are broken (goes to localhost:4000). i think commit around 09 Feb 2017 21:15 UTC +0700 broke it.

**Comment by michel-kraemer** [comment]
Thanks for reporting. It's already been fixed.

See this thread:
https://groups.google.com/forum/#!topic/vertx-dev/1qEYdQ38BqQ
