### ISSUE TITLE
httpclient usage question?

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#195]
Hi there:

We currently have a question about how to use httpclient.
since if we put http client instance in the verticle as a verticle attribute, like this:

    public class MyVerticle extends AbstractVerticle {

    HttpClient httpClient;
    
    public void start() throws Exception {

        HttpClient httpClient = vertx.createHttpClient();
        //...http client usage
    }
    }

then a deadlock could be detected

Found one Java-level deadlock:

"vert.x-eventloop-thread-47":
  waiting to lock monitor 0x000000001a182748 (object 0x00000000da863a70, a io.vertx.core.http.impl.HttpClientRequestImpl),
  which is held by "vert.x-eventloop-thread-0"
"vert.x-eventloop-thread-0":
  waiting to lock monitor 0x000000001e851bb8 (object 0x00000000ff6253f8, a io.vertx.core.http.impl.ClientConnection),
  which is held by "vert.x-eventloop-thread-47"

and the system becomes very slow

we checked the official doc and about this part it is not very clear to us since it shows:

> The HttpClient can be used in a Verticle or embedded.
> 
> When used in a Verticle, the Verticle should use its own client instance.

not sure "use its own client instance" means but from our understanding, the verticle is using its own client instance.

and we continue reading the doc below it shows:

> More generally a client should not be shared between different Vert.x contexts as it can lead to unexpected behavior.

some people believe that one http client should be bound to an eventloop context then the code should be:

    public class MyVerticle extends AbstractVerticle {
    
    public void start() throws Exception {
        //Context context = vertx.getOrCreateContext();
        HttpClient httpClient = context.get("client");
        if(httpClient==null){
            httpClient = vertx.createHttpClient();
            context.put("client",httpClient);
        }
        // http client usage
    }
    }

It seems OK and we are testing this way of usage, but still not sure this is the correct way to do it
So would you mind elaborating this part please?

Thank you very much

Best regards

**Comment by michel-kraemer** [comment]
@chengenzhao This is the issue tracker for the Vert.x website. Please post your message to the Vert.x google group.
https://groups.google.com/forum/?fromgroups#!forum/vertx

There are a lot of people in this group who can help you much better than we can here in the issue tracker. Also you should get an answer a lot faster. Thanks.
