### ISSUE TITLE
Missing text in core explanation?

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#207]
Hi there:

In the core doc, there is a paragraph saying "If you’re using Verticles"
and there is no other contents and following is a note
It seems like here we should say If u r using Verticles, then there is a build-in vertx object blablabla

Hope it helps

**Comment by tsegismont** [comment]
Thanks for pointing this out. I sent a pull request to Vert.x core.

2017-04-04 1:38 GMT+02:00 Chengen Zhao <notifications@github.com>:
