### ISSUE TITLE
blocking code pool?

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#210]
Hi there:

On the core document, it says

"By default blocking code is executed on the Vert.x blocking code pool, configured with setWorkerPoolSize."

I think here it means worker pool rather than blocking code pool which may cause confusion for readers.

Just my opinion

hope it helps

**Comment by tsegismont** [comment]
Sounds goods as it is called worker pool in other places. Would like to
contribute the change?

2017-04-07 19:49 GMT+02:00 Chengen Zhao <notifications@github.com>:

**Comment by chengenzhao** [comment]
Sure, I just submitted an enhancement PR for this doc, hope it helps

Cheers
