### ISSUE TITLE
Horizontal scrolling not working properly for one of the tutorials

### ISSUE THREAD

**Issue by kraulain** [vert-x3/vertx-web-site#211]
I was going through the tutorial at  http://escoffier.me/vertx-hol/ gotten from http://vertx.io/materials/#tutorials when i realized that it was possible to scroll horizontally such that text overlaps text and its no longer very readable as shown in the attached screenshot
![image](https://cloud.githubusercontent.com/assets/11361413/24908706/f443752e-1eb8-11e7-8a01-39c99b464131.png)
This might just be a slight CSS issue but i think its worth fixing.
I am using Google chrome Version 57.0.2987.133 (64-bit)

**Comment by cescoffier** [comment]
Has been fixed.
