### ISSUE TITLE
Stephane Epardaud adds hiself to the Vert.x committers

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-web-site#220]

**Comment by FroMage** [comment]
OK, where's that list?

**Comment by vietj** [comment]
https://github.com/vert-x3/vertx-web-site/blob/master/src/generated/community/contributors-gen.js

**Comment by FroMage** [comment]
OK thanks.

**Comment by FroMage** [comment]
Done.

**Comment by cescoffier** [comment]
Did someone republish the web site ?

**Comment by cescoffier** [comment]
^ (doing it)

**Comment by FroMage** [comment]
Oh, it's not automatic?

**Comment by cescoffier** [comment]
No but it could.
