### ISSUE TITLE
Website should run primarily on https

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-web-site#232]
This is a small thing, but it is about perception and quality.
Nowadays it is considered best-practice that all websites are secure, redirecting http traffic to https.
Most of the popular technology websites already do this. I was surprised to see vert.x didn't.

Thanks!

**Comment by pmlopes** [comment]
@aschrijver This is mostly a technical issue with github at the moment since gh-pages do not allow HTTPS. Other providers do allow it e.g.: gitlab but github doesn't and there is no feedback from their side when/if they will do it too.

**Comment by alexlehm** [comment]
We talked about enabling this with Cloudflare while back, but have not done an implementation

Can't find the thread right now, i will add it when i find it

**Comment by aschrijver** [comment]
Cool :thumbsup:

**Comment by pmlopes** [comment]
@alexlehm do you mean this: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by amdelamar** [comment]
_Bump_. Please enable this soon.

Another Eclipse project-website, MicroProfile https://microprofile.io/ is using CloudFlare already for HTTPS (and HTTP/2 for that matter). Here is their [website repo](https://github.com/microprofile/microprofile-site#summary) explaining the setup.
