### ISSUE TITLE
Missing link in Vert.x Documentation for MQTT

### ISSUE THREAD

**Issue by minosniu** [vert-x3/vertx-web-site#246]
The "Examples" link in this section is broken: [http://vertx.io/docs/#mqtt](http://vertx.io/docs/#mqtt)

which points to: [https://github.com/vert-x3/vertx-examples/tree/master/mqtt-server-examples](https://github.com/vert-x3/vertx-examples/tree/master/mqtt-server-examples)

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
fixed
