### ISSUE TITLE
Vert.x Rx examples links are broken

### ISSUE THREAD

**Issue by theoweiss** [vert-x3/vertx-web-site#250]
The examples links for Vert.x Rx in this section are broken: http://vertx.io/docs/#reactive

**Comment by tsegismont** [comment]
@theoweiss nice catch, thanks!

**Comment by tsegismont** [comment]
Fixed via https://github.com/vert-x3/vertx-web-site/commit/2029be67ced4339b484eae7ce2a57d9a9b3216cb
