### ISSUE TITLE
Remove Vert.x 2.x docs

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-web-site#258]

**Comment by cescoffier** [comment]
Do we just drop them and remove the link?

**Comment by vietj** [comment]
for safety purpose, let's just remove the link and keep the actual content for a while

**Comment by michel-kraemer** [comment]
Before removing the content later, I would set a permanent redirect from all 2.x pages to vert.io (index.html). This will allow search engines to update their index.
