### ISSUE TITLE
Using mqtt server doesn't load css

### ISSUE THREAD

**Issue by IDerr** [vert-x3/vertx-web-site#286]
Hi :D 
When loading : [mqtt server](https://vertx.io/docs/vertx-mqtt-server/java/#_using_vert_x_mqtt_server),
the css is not loading because of mixed http and https.

Thanks a lot for your work

**Comment by cescoffier** [comment]
@IDerr the module has been renamed to Vert.x MQTT. Check https://vertx.io/docs/vertx-mqtt/java/#_using_vert_x_mqtt_server.

**Comment by IDerr** [comment]
Thanks a lot for the fast answer.
