### ISSUE TITLE
Wrong content for GraphQL documentation

### ISSUE THREAD

**Issue by AhmedMKamal** [vert-x3/vertx-web-site#315]
Please double check the GraphQL Kotlin documentation [dependencies section](https://vertx.io/docs/vertx-web-graphql/kotlin/#_getting_started) it should be `io.vertx:vertx-web-graphql:3.7.1` not `io.vertx:vertx-lang-kotlin:3.7.1` in both Maven and Gradle dependencies, thanks.

**Comment by tsegismont** [comment]
Thanks for reporting. I'll take care of it.

Le sam. 8 juin 2019 à 10:40, Ahmed M.Kamal <notifications@github.com> a
écrit :

**Comment by tsegismont** [comment]
Moved to https://github.com/vert-x3/vertx-web/issues/1311
