### ISSUE TITLE
Write a post for incoming vertx-sql-client in the 3.8.0 release

### ISSUE THREAD

**Issue by BillyYccc** [vert-x3/vertx-web-site#318]
including a statement for the progress of the relevant GSoC 2019 project (MSSQL support)

**Comment by vietj** [comment]
it will be announce first in 3.8.0 release, do you want a separate post only for the client or a section of the release blog post ?

**Comment by BillyYccc** [comment]
Maybe we can write a more detailed separate post ahead of the 3.8.0 release post and add the reference link in the 3.8.0 release post?

**Comment by vietj** [comment]
I'm planning to release this week 3.8.0 so it would not be written yet I think
