### ISSUE TITLE
Broken link in core manual

### ISSUE THREAD

**Issue by thokari** [vert-x3/vertx-web-site#327]
Under the [Json Pointers](https://vertx.io/docs/vertx-core/java/#_json_pointers) section is a hyperlink shown as markup, unable of being clicked.

**Comment by tsegismont** [comment]
Fixed in https://github.com/eclipse-vertx/vert.x/commit/76591546472c92de87345e2e8750cc8533c9682c

**Comment by tsegismont** [comment]
Thanks for the report
