### ISSUE TITLE
Add an entrance for different version?

### ISSUE THREAD

**Issue by cpdyj** [vert-x3/vertx-web-site#334]
Is it a good idea that add an entrance for multiple version on all website?

**Comment by vietj** [comment]
do you mean multiple version of the doc ?

**Comment by cpdyj** [comment]
Yeah, maybe we can provide a page of multiple version docs's link.

In fact, I found the docs of 4.0 version until yesterday. (x


在 2020/1/5 2:18, Julien Viet 写道:

**Comment by vietj** [comment]
4.0 docs are for now on a separate web-site

we keep all docs but in fact we don't provide links for the pages.

I think somehow we should provide them

**Comment by vietj** [comment]
e.g https://vertx.io/docs/3.6.2/vertx-core/java/

**Comment by vietj** [comment]
and https://vertx.io/docs/3.6.2/

**Comment by cpdyj** [comment]
@vietj 
Maybe deploy it in sperate website is a good idea.(x
So the simplest way is add a page of links?
I means maybe we can add a page in a standalone space which provides a set of links refer to different version. And add a link refer to this page in all docs site.
Is it a good idea?

**Comment by vietj** [comment]
I believe we should find a decent place in the website to link to previous versions, e.g the docs page itself should link to previous versions at the bottom, or something else

**Comment by cpdyj** [comment]
I think it's useful.2020年1月6日 下午6:01，Julien Viet <notifications@github.com>写道：I believe we should find a decent place in the website to link to previous versions, e.g the docs page itself should link to previous versions at the bottom, or something else
