### ISSUE TITLE
missing page - vertx-junit5-web-client

### ISSUE THREAD

**Issue by badape-github** [vert-x3/vertx-web-site#346]
### Issue

https://vertx.io/docs/vertx-junit5-web-client/java/ returns a 404 page not found.

### Version

3.9.2

### Steps to reproduce

https://vertx.io/docs/vertx-junit5/java/#_junit_5_additional_extensions

click link to https://vertx.io/docs/vertx-junit5-web-client/java/

see 404 error

**Comment by jponge** [comment]
This is expected, the module was moved to https://reactiverse.io/reactiverse-junit5-extensions/
