### ISSUE TITLE
Wrong entry link in blog's feed

### ISSUE THREAD

**Issue by bataillec** [vert-x3/vertx-web-site#351]
### Context

I encountered an error 404 page when following article link in blog feed. It seems a "/blog" has been forgotten in entry link.

### Steps to reproduce

1. Go to https://vertx.io/blog/
2. Click on feed icon on the right
3. On https://vertx.io/feed/atom.xml , each blog entry has a link. Example: https://vertx.io/whats-new-in-vert-x-4
4. Following the entry link, fall on error 404  page
5. Fix the link adding "/blog". Example : https://vertx.io/blog/whats-new-in-vert-x-4
6. It works !

**Comment by tsegismont** [comment]
Nice catch, thanks for reporting!

Le ven. 19 févr. 2021 à 11:23, bataillec <notifications@github.com> a
écrit :
