### ISSUE TITLE
Retina compatible images (such as favicon and reactive ribbon)

### ISSUE THREAD

**Issue by newoga** [vert-x3/vertx-web-site#4]

**Comment by newoga** [comment]
One approach is to adapter a pure CSS ribbon insteado of use an image such as http://codepo8.github.io/css-fork-on-github-ribbon

**Comment by michel-kraemer** [comment]
* We don't have a ribbon anymore. So nothing to do here.
* I created a new favicon that is compatible to various devices  
  (thanks to https://realfavicongenerator.net)

<img src="https://cloud.githubusercontent.com/assets/295407/14049116/56f16a7e-f2b3-11e5-96af-e702c5414b9c.png" width="32" height="32">

@cescoffier You may restage the website whenever you feel like it.

**Comment by michel-kraemer** [comment]
@vietj @cescoffier @pmlopes Just an idea. Maybe we can also use the new favicon as the avatar for the github group (https://github.com/vert-x3)? A 512x512 pixels version can be found in the favicons folder.

**Comment by cescoffier** [comment]
@michel-kraemer done, Thanks !
