### ISSUE TITLE
Make reactive ribbon non-sticky (or header sticky)

### ISSUE THREAD

**Issue by newoga** [vert-x3/vertx-web-site#5]
Maybe we should consider making the reactive ribbon non-sticky like the header or make the header sticky like it was in original design. I'm fine with either approach :)

**Comment by purplefox** [comment]
Not sure if this is still an issue..

**Comment by newoga** [comment]
Yeah, we can close this. I think on the older website, the header was non-sticky so only the ribbon was moving around as you scrolled which seemed odd. On the current website, the reactive ribbon floats with the header so I think it looks alright now.

Closing this...
