### ISSUE TITLE
Create "awesome-vertx" GitHub project

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#54]
Originally proposed by @newoga

"Another approach for listing related community projects is to create a curated list of them as a github repo.

examples: https://github.com/avelino/awesome-go, https://github.com/vinta/awesome-python

We could highlight a repository like that on the community page, and it'd also have the benefit of having visibility on github.
"

**Comment by purplefox** [comment]
The awesome repo now exists, but we should link to it from the community page.

**Comment by newoga** [comment]
Nice! Yeah after adding it to the community page, we can probably close this.

Would it be worthwhile creating a post in vertx or vertx-dev google groups about the vertx-awesome repo? Might be an opportunity to get a sense of what people have developed or are working on outside of vertx-ext...

**Comment by michel-kraemer** [comment]
@purplefox Yes, I agree with @newoga. It would be great if you could announce it on the mailing list. I would also suggest adding a section with tutorials and (real-life) examples.

**Comment by cescoffier** [comment]
The community page has now a link to the vert.x awesome project. 
So, we just need to make an announcement.

**Comment by purplefox** [comment]
We should also consider whether we're going to add the equivalent for Vert.x 2 to this page:

https://github.com/eclipse/vert.x/wiki/Useful-Vert.x-components-and-modules

**Comment by cescoffier** [comment]
We could migrate the page to the a "vert.x 2 awesome" project to just create a vert.x 2 file on the same repo (vert.x 3 organisation).

WDYT ?

**Comment by purplefox** [comment]
+1 to that suggestion.

Also, feel free to announce on the google group :)

**Comment by cescoffier** [comment]
Announce done, closing the issue.
