### ISSUE TITLE
Add origami3 to Who's using Vert.x page

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#57]
link: origami3.com

**Comment by purplefox** [comment]
![origami3](https://cloud.githubusercontent.com/assets/701906/8023119/c0c4ada4-0cf3-11e5-906a-bfc17d8a94d3.png)

**Comment by michel-kraemer** [comment]
Do you know if they have a logo with letters? It would look a bit better. But of course I can also add it like this.

**Comment by maumock** [comment]
![logo-vertx](https://cloud.githubusercontent.com/assets/2142058/8145053/80dc67a6-11b5-11e5-98dc-ddb7580b6973.png)

SVG, in white, will be sent through email. Please make any necessary adjustments to the SVG.

**Comment by michel-kraemer** [comment]
Thanks. Merged.
