### ISSUE TITLE
Add phenixid to "Who's using Vert.x?" page

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#59]
Link: http://www.phenixid.net/

**Comment by purplefox** [comment]
Awaiting logo

**Comment by cpetersson** [comment]
Attached is the phenixid logo. Have fun! ;)

![phenixid_mono_white](https://cloud.githubusercontent.com/assets/1038329/8033814/e94d7cf8-0de1-11e5-994e-6577cf7bd904.png)

**Comment by michel-kraemer** [comment]
@cpetersson Thanks for the well-prepared file! :-)
