### ISSUE TITLE
Add vertixone to "Who's using Vert.x?" section

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#60]
link: www.vertixone.com

![vertix](https://cloud.githubusercontent.com/assets/701906/8023146/6843e4cc-0cf5-11e5-82ed-1881bf83fa3c.png)

**Comment by michel-kraemer** [comment]
I will add it. I just couldn't find the right website. Do you know if they have a larger version of the logo. I'd rather scale it down than up.

P.S.: Is the website down at the moment?

**Comment by celsiux** [comment]
Hello Michael please find below a bigger size of the logo, site is online

![vertix-logo](https://cloud.githubusercontent.com/assets/1435843/8163211/c5803aea-134f-11e5-8bc9-f2b707ea709d.png)

Let me know if you need the logo in different format or size.

Best Regards,

**Comment by michel-kraemer** [comment]
Thanks! :)
