### ISSUE TITLE
Add sketchtogether to "Who's using Vert.x?" section

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#61]
link: sketchtogether.com

![sketchtogether](https://cloud.githubusercontent.com/assets/701906/8023155/aa518c2a-0cf5-11e5-8098-0d2317a571d7.png)

**Comment by michel-kraemer** [comment]
On their website they have a nice logo with letters. It would look a bit better on the Vert.x page. Do you know if they specifically prefer this one (without text)?

**Comment by nfmangano** [comment]
Hi Tim and Michel, 

Glad you guys like the logo. Regarding a logo that you can use, here's both a monochromatic and regular versions of the logo above with text:

* Monochromatic logo: https://www.dropbox.com/s/cpoae4eej6v6w88/st_banner_mono.svg?dl=0
* Regular logo with text: https://www.dropbox.com/s/rak7tgx7hvy3unt/st_banner.svg?dl=0

Let me know if you guys need it in another format.

**Comment by purplefox** [comment]
@michel-kraemer l - these logos don't have a transparent background and I struggled to convert them, so deferring to your better photoshop skills on this :)

**Comment by michel-kraemer** [comment]
Done. I just opened the first svg file in Inkscape and exported it as PNG :-)
