### ISSUE TITLE
Move cyanogen to home page in "Who's using Vert.x?"

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#62]
I think we should move cyanogen to the homepage as they have a wikipedia page and are a very high profile startup:

http://en.wikipedia.org/wiki/CyanogenMod

**Comment by michel-kraemer** [comment]
:) I didn't realize it's the same company. The logo on the Wikipedia page is still the old one I guess. Stupid me.

The wikipedia page doesn't list revenue or number of employees, so my simple sorting algorithm won't put them on the home page. Also, at the moment we have eight companies there and nine would look a bit odd (I guess 11 or 12 would look much better, should we decide to increase the number).

Any suggestions?

**Comment by purplefox** [comment]
I increased the number to 12 which doesn't look too bad, also we're probably have more before we release 3.0 anyway :)
