### ISSUE TITLE
TouK logo on Vertx page

### ISSUE THREAD

**Issue by zdanek** [vert-x3/vertx-web-site#68]
Hi.
I'm attaching TouK logo.
It should link to http://touk.pl

We love vert.x here.
![touk180x180monochrome-01](https://cloud.githubusercontent.com/assets/440614/8053076/64dc4d12-0e8d-11e5-93b8-7dd1b484e316.png)

Personally I'm vert.x advocate :D

**Comment by zdanek** [comment]
The logo is in between "We love vert.x here." and "Personally I'm vert.x advocate :D"  It's white on transparent background :) In case of any problems please let me know.

**Comment by michel-kraemer** [comment]
Thanks!
