### ISSUE TITLE
Vert.x use case in Spain

### ISSUE THREAD

**Issue by 4yestaran** [vert-x3/vertx-web-site#73]
Hello Tim,

as agreed by email, we open this issue to document a  Vert.x use case.

We are an Spanish digital solutions provider (Paradigma Tecnológico) and we have used Vert.x in one of the most important retail companies in Spain.

The project is really important, some details about it:

Goal: unify all user information databases to have a consolidated view throughout all the company businesses.

Solution: we developed a lightweight service layer in Vert.x over MongoDB. This layer adds to MongoDB the business logic and validations needed to ensure data quality and integrity.

Some highlights: 
15.000.000 customers
Service load: +2.000 read requests per second

Attached you can find our logo. Our URL is www.paradigmatecnologico.com 

Don’t hesitate to contact me if you have any doubts.

Thanks,
— 
Diego Mosquera

![logo_paradigma_2013](https://cloud.githubusercontent.com/assets/6450065/8238828/6343d4bc-15f8-11e5-8700-3a06ec4e7f4f.png)

**Comment by purplefox** [comment]
Thanks, done.
