### ISSUE TITLE
Copy Vert.x 2 website into sub directory of Vert.x 3 site

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#74]
We need to copy the current Vert.x 2 website into the Vert.x 3 web site, so that when we switch over vertx.io to use the new Vert.x 3 website, the Vert.x 2 site is still available

**Comment by purplefox** [comment]
@michel-kraemer Any idea how to do this? I tried a naive copy of the old site into a directory src/site/vertx2 but the site build fails as it doesn't seem to be expecting static resources.

**Comment by michel-kraemer** [comment]
I updated the build script. Please copy the old website to `src/main/vertx2` instead of `src/site/vertx2`.
