### ISSUE TITLE
Add page with links to articles and videos about Vert.x

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#76]
(after 3.0)

**Comment by cescoffier** [comment]
since we have now a couple of presentation and video, this issue makes a lot of sense.

**Comment by purplefox** [comment]
We have more than a few :)

https://github.com/vert-x3/wiki/wiki/Presentations-about-Vert.x

**Comment by cescoffier** [comment]
Did you add the recent ones ;-)

Will work on a page before the end of the week.
