### ISSUE TITLE
Order contributors by size of contribution

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#80]
I'm not sure if it is possible to get this info from the GitHub API but...

... it would be cool if we could some order the community contributor list by size of contributions (lines of code?) so we could display those who have made bigger contributions at the top, and those who had just made a very small contrib at the bottom.

**Comment by michel-kraemer** [comment]
Yes, I guess I can implement this. I'll be out of office for the next two weeks (one week business and one week vacation). Do you think it's OK if I do it when I'm back?

**Comment by zdanek** [comment]
Will you automate the script to be run periodically? As people come and go, and the side of their commits changes :)

**Comment by purplefox** [comment]
I think we should also keep the ability to override the ordering and have the "hardcoded" ones at the top of the list (like we currently do).

No hurry on this one :)
