### ISSUE TITLE
Blog area on the website

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#81]
I think this was discussed before to some degree, but I think it would be great to have blog functionality in the web site so members of the team could blog about Vert.x related stuff.

Then we can output an RSS feed that could be aggregated elsewhere e.g. on the jboss.org or eclipse.org sites.

**Comment by purplefox** [comment]
I've tried and failed to get GitHub's recommended solution: Jekyll working - so I'm going to rule that out.

**Comment by vietj** [comment]
how surprising :-)

**Comment by purplefox** [comment]
And please no-one suggest any other Ruby based tools ;)

**Comment by pmlopes** [comment]
I've picked poole and quickly installed and used my domain: https://github.com/pmlopes/pmlopes.github.io I just followed the instructions and it worked for me both on Ubuntu 14.04 and Fedora 22

**Comment by vietj** [comment]
we need something that makes easy to write code with syntax color or gists.

**Comment by vietj** [comment]
perhaps we can setup something like Jekyll once and for all and let Jenkins build/push it from a "blog" source repo ?

**Comment by cescoffier** [comment]
Yes, this is probably the simplest.

**Comment by pmlopes** [comment]
poole/jekyll can have code with syntax highlight just do:

```
{% highlight java %}
public interface Empty {}
{% endhighlight %}
```

**Comment by vietj** [comment]
it would be nice to use a system that has a docker image for easy usage locally.

**Comment by michel-kraemer** [comment]
The website is based on metalsmith.io which can already be used as a blog generator. We don't need Jekyll or anything else. It's got a lot of plugins including a markdown renderer, syntax highlighter and everything else you typically need for a software development related blog.

Too bad I'll have to leave for a business trip tomorrow. Otherwise I would have been able to set the whole thing up for you. In any case I will be able to answer questions by email and assist you if you want to try to set it up yourself.

**Comment by cescoffier** [comment]
Would be really nice to keep the same tools (and so avoid the divergence). I don't know metalsmith but I'm going to have a look.

**Comment by michel-kraemer** [comment]
Here are some things I remember from a previous project. Note that I have not tested the following snippets. Consider them as **pseudo-code**:

Put the following in the `gulpfile.js` before line 125 (before the templates are applied):

```javascript
.use(branch()
    .pattern('site/blog/*.md')  // only for *.md source files under 'site/blog/
    .use(metallic())            // apply highlight.js (must appear before markdown()!)
    .use(markdown())            // generate html
)
```

Of course you need

```javascript
var branch = require('metalsmith-branch')
var markdown = require('metalsmith-branch')
var metallic = require('metalsmith-metallic');
```

and

```bash
npm install --save-dev metalsmith-branch metalsmith-markdown metalsmith-metallic
```

Here are some links:
http://www.metalsmith.io/
https://github.com/ericgj/metalsmith-branch
https://github.com/segmentio/metalsmith-markdown
https://github.com/weswigham/metalsmith-metallic

Hope this helps. This should get you to the point where you have a simple blog. You need the `collections` plugin to mark files under `site/blog` as blog posts. This will allow you to generate a list of blog posts (i.e. pages from this collection) anywhere on the site through the template mechanism. Furthermore you might want to have a look at the `pagination` plugin once there are more than five posts or so.

Cheers,
Michel

**Comment by cescoffier** [comment]
Thanks @michel-kraemer 

Your instructions are very useful. It's mostly there. Gonna finish this on Monday. 
Thanks again for your help

**Comment by cescoffier** [comment]
Blog is there !

Instructions for posting are here: https://github.com/vert-x3/vertx-web-site/tree/web-site-3.0.0#the-blog

When the first post will be available, I will add the header links.

**Comment by cescoffier** [comment]
(will close once the first post will be published).

**Comment by sirgantrithon** [comment]
I'm not sure if I should create a new issue or add to this one, but I'm getting some layout bugs at the bottom of the blog.  I have attached a screenshot.

![image](https://cloud.githubusercontent.com/assets/3400609/8459627/9010a3fa-1fec-11e5-8b73-b7912fe79457.png)

**Comment by cescoffier** [comment]
Thanks for reporting, did not see it. I think I know the issue.

On 1 juil. 2015, at 18:28, Ian Andrews <notifications@github.com> wrote:

I'm not sure if I should create a new issue or add to this one, but I'm
getting some layout bugs at the bottom of the blog. I have attached a
screenshot.

[image: image]
<https://cloud.githubusercontent.com/assets/3400609/8459627/9010a3fa-1fec-11e5-8b73-b7912fe79457.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/vert-x3/vertx-web-site/issues/81#issuecomment-117738228>
.

**Comment by cescoffier** [comment]
I've fixed the double footer as well as a missing `</div>` in a template.

**Comment by cescoffier** [comment]
As the blog is functional, I'm closing this issue.
