### ISSUE TITLE
Missing import statement for Java hello world example on the front page

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/vertx-web-site#85]
Hi there, on the front page of the new website
 the Java hello world example is:

//import io.vertx.core.AbstractVerticle;
/*this line is missing, please add in this line otherwise the vert.x will not be able to find the class: AbstractVerticle and throw out an exception*/

public class Server extends AbstractVerticle {
  public void start() {
    vertx.createHttpServer().requestHandler(req -> {
      req.response()
        .putHeader("content-type", "text/plain")
        .end("Hello from Vert.x!");
    }).listen(8080);
  }
}

**Comment by cescoffier** [comment]
There is also an issue in the ruby example (must be `$vertx` instead of `vertx`)

**Comment by cescoffier** [comment]
Fix deployed.
