### ISSUE TITLE
Blog feed only provides blog snippets

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#91]
Vert.x blog is now aggregated at jboss.org:

https://planet.jboss.org/#projects=vertx

They raised the point that currently we are only exporting snippets of blog entries in the feed, not the whole entry.

They'd like to see the whole thing. Is this possible?

**Comment by cescoffier** [comment]
Yes, it's possible. Right now I was using excerpt (kind of complicated to compute BTW).

**Comment by cescoffier** [comment]
Done.
