### ISSUE TITLE
eProcurement Indonesia - Powerfull eProcurement Software using Vert.x Technology

### ISSUE THREAD

**Issue by eriyanto** [vert-x3/vertx-web-site#94]
![eprocurement-indonesia-logo](https://cloud.githubusercontent.com/assets/11383742/8647170/bfd7a498-297f-11e5-9580-a43371c399a9.png)

Dear Tim Fox,
Thank You So Much for Your Response. herewith i attach my logo and i you need
to view detail about eProcurement Indonesia, you can see detail at http://eprocurement-indonesia.com/

Thank You

**Comment by purplefox** [comment]
Hi, can you edit the logo?- it needs to be in white on a transparent background and 180px width.

Take a look at the other logos on the website for examples :)

Thanks!

**Comment by eriyanto** [comment]
Dear Tim Fox,
Sorry for late response, because of overseas work.
herewith i attached logo eprocurement indonesia in accordance with your suggestion.

Thank You so much for your attention.

Eriyanto
![eprocurement-indonesia-180px](https://cloud.githubusercontent.com/assets/11383742/9189143/92b07cec-400e-11e5-8d6f-b9de3a0ccf3e.png)

**Comment by purplefox** [comment]
Thanks!
